use elga;

SELECT MEDICAL_CASE.STATUS             as MEDICAL_CASE_STATUS,
       MEDICAL_CASE.DATE_FROM          as MEDICAL_CASE_DATE_FROM,
       MEDICAL_CASE.DATE_TO            as MEDICAL_CASE_DATE_TO,

       CLASSIFICATION_SYSTEM.NAME      as CLASSIFICATION_SYSTEM_NAME,
       CLASSIFICATION_SYSTEM.FREQUENCY as CLASSIFICATION_SYSTEM_FREQUENCY,
       CLASSIFICATION_SYSTEM.NUMBER    as CLASSIFICATION_SYSTEM_NUMBER,

       PATIENT.DATE_CREATED            as PATIENT_DATE_CREATED,
       PATIENT.FIRSTNAME               as PATIENT_FIRSTNAME,
       PATIENT.SURNAME                 as PATIENT_SURNAME,
       PATIENT.DATEOFBIRTH             as PATIENT_DATE_OF_BIRTH,
       PATIENT.SEX                     as PATIENT_SEX,
       PATIENT.WEIGHT                  as PATIENT_WEIGHT,
       PATIENT.HEIGHT                  as PATIENT_HEIGHT,
       PATIENT.TITLE                   as PATIENT_TITLE,
       ADDRESS.ZIP_CODE                as PATIENT_ZIP_CODE,
       REGION.NAME                     as PATIENT_REGION,

       HOSPITAL.NAME                   as HOSPITAL_NAME,
       HOSPITAL.NAME_SHORT             as HOSPITAL_NAME_SHORT,
       HOSPITAL.CAPACITY               as HOSPITAL_CAPACITY,
       HOSPITAL.ZIP_CODE               as HOSPITAL_ZIP_CODE,

       DOCTOR.DATE_CREATED             as DOCTOR_DATE_CREATED,
       DOCTOR.FIRSTNAME                as DOCTOR_FIRSTNAME,
       DOCTOR.SURNAME                  as DOCTOR_SURNAME,
       DOCTOR.DATEOFBIRTH              as DOCTOR_DATE_OF_BIRTH,
       DOCTOR.SEX                      as DOCTOR_SEX,
       DOCTOR.TITLE                    as DOCTOR_TITLE,
       DOCTOR.DATEOFBIRTH              as DOCTOR_DATE_OF_BIRTH,

       MEDICAL_VISIT.COSTS_PER_DAY     as MEDICAL_VISIT_COSTS_PER_DAY,
       MEDICAL_VISIT.RATING            as MEDICAL_VISIT_RATING,
       MEDICAL_VISIT.DATE_FROM         as MEDICAL_VISIT_DATE_FROM,
       MEDICAL_CASE.DATE_TO            as MEDICA_VISIT_DATE_TO

FROM MEDICAL_CASE,
     CLASSIFICATION_SYSTEM,
     PATIENT,
     ADDRESS,
     REGION,
     HOSPITAL,
     DOCTOR,
     MEDICAL_VISIT
WHERE CLASSIFICATION_SYSTEM.CS_ID = MEDICAL_CASE.CS_ID_DIAGNOSIS
  AND PATIENT.PATIENT_ID = MEDICAL_CASE.PATIENT_ID
  AND ADDRESS.PATIENT_ID = PATIENT.PATIENT_ID
  AND REGION.REGION_ID = ADDRESS.REGION_ID
  AND HOSPITAL.HOSPITAL_ID = MEDICAL_CASE.HOSPITAL_ID
  AND DOCTOR.DOCTOR_ID = MEDICAL_CASE.DOCTOR_ID_REF
  AND MEDICAL_VISIT.MEDICAL_CASE_ID = MEDICAL_CASE.MEDICAL_CASE_ID


-- Rang eines Arztes basierend auf der Anzahl der Fälle pro Krankenhaus:
SELECT DOCTOR.SURNAME AS Surname, HOSPITAL.NAME, COUNT(MEDICAL_CASE_ID) AS CASE_COUNT,
       RANK() OVER (PARTITION BY MEDICAL_CASE.HOSPITAL_ID ORDER BY COUNT(MEDICAL_CASE_ID) DESC) AS DOCTOR_RANK
FROM MEDICAL_CASE
         JOIN DOCTOR ON MEDICAL_CASE.DOCTOR_ID_REF = DOCTOR.DOCTOR_ID
         JOIN HOSPITAL ON MEDICAL_CASE.HOSPITAL_ID = HOSPITAL.HOSPITAL_ID
GROUP BY DOCTOR.SURNAME, HOSPITAL.NAME, MEDICAL_CASE.HOSPITAL_ID;

-- Summe der Anzahl der medizinischen Fälle pro Arzt:
SELECT DOCTOR.SURNAME,
       SUM(COUNT(MEDICAL_CASE.MEDICAL_CASE_ID)) OVER (PARTITION BY DOCTOR.DOCTOR_ID ORDER BY DOCTOR.SURNAME) AS SUM
FROM MEDICAL_CASE
         JOIN DOCTOR ON MEDICAL_CASE.DOCTOR_ID_REF = DOCTOR.DOCTOR_ID
GROUP BY DOCTOR.SURNAME, DOCTOR.DOCTOR_ID;

-- vorherige Diagnose gruppiert nach Patient:
SELECT P.SURNAME AS PATIENT_SURNAME, CS.NAME AS DIAGNOSIS,
       LAG(CS.NAME) OVER (PARTITION BY M.PATIENT_ID) AS PREVIOUS_DIAGNOSIS
FROM MEDICAL_CASE M
         JOIN PATIENT P ON M.PATIENT_ID = P.PATIENT_ID
         JOIN CLASSIFICATION_SYSTEM CS ON M.CS_ID_DIAGNOSIS = CS.CS_ID
ORDER BY P.PATIENT_ID;
-- durchschnittliche Anzahl von Fällen pro Patient und Krankenhaus:
SELECT P.SURNAME AS SURNAME,P.FIRSTNAME AS FIRSTNAME, H.NAME AS HOSPITAL_NAME,
       AVG(COUNT(M.MEDICAL_CASE_ID)) OVER (PARTITION BY P.PATIENT_ID) AS AVG_CASE_COUNT
FROM MEDICAL_CASE M
         JOIN PATIENT P ON M.PATIENT_ID = P.PATIENT_ID
         JOIN HOSPITAL H ON M.HOSPITAL_ID = H.HOSPITAL_ID
GROUP BY P.PATIENT_ID, M.HOSPITAL_ID, H.NAME, P.SURNAME;
-- Summe der Anzahl der Fälle pro Arzt und Krankenhaus:
SELECT D.SURNAME AS SURNAME, H.NAME AS HOSPITAL_NAME,
       SUM(COUNT(M.MEDICAL_CASE_ID)) OVER (PARTITION BY D.DOCTOR_ID, M.HOSPITAL_ID) AS CNT,
       MCD.NAME AS MEDICAL_CASE
FROM MEDICAL_CASE M
         JOIN DOCTOR D ON M.DOCTOR_ID_REF = D.DOCTOR_ID
         JOIN HOSPITAL H ON M.HOSPITAL_ID = H.HOSPITAL_ID
         JOIN CLASSIFICATION_SYSTEM MCD ON M.CS_ID_DIAGNOSIS = MCD.CS_ID
GROUP BY D.DOCTOR_ID, M.HOSPITAL_ID, H.NAME, D.SURNAME, MCD.CS_ID;




