use elga;

select HOSPITAL.NAME, CLASSIFICATION_SYSTEM.NAME
from  HOSPITAL,MEDICAL_CASE,CLASSIFICATION_SYSTEM
WHERE HOSPITAL.HOSPITAL_ID = MEDICAL_CASE.HOSPITAL_ID && MEDICAL_CASE.CS_ID_DIAGNOSIS = CLASSIFICATION_SYSTEM.CS_ID
GROUP BY HOSPITAL.NAME;



SELECT *
FROM MEDICAL_CASE
JOIN HOSPITAL ON HOSPITAL.HOSPITAL_ID = MEDICAL_CASE.HOSPITAL_ID
JOIN CLASSIFICATION_SYSTEM ON CLASSIFICATION_SYSTEM.CS_ID = MEDICAL_CASE.CS_ID_DIAGNOSIS
JOIN PATIENT ON PATIENT.PATIENT_ID = MEDICAL_CASE.PATIENT_ID
JOIN DOCTOR ON DOCTOR.DOCTOR_ID = MEDICAL_CASE.DOCTOR_ID_REF;

SELECT HOSPITAL.NAME AS Hospital, CLASSIFICATION_SYSTEM.NAME AS Diagnosis, COUNT(MEDICAL_CASE.MEDICAL_CASE_ID) AS Case_Count
    FROM HOSPITAL
    JOIN MEDICAL_CASE ON HOSPITAL.HOSPITAL_ID = MEDICAL_CASE.HOSPITAL_ID
    JOIN CLASSIFICATION_SYSTEM ON CLASSIFICATION_SYSTEM.CS_ID = MEDICAL_CASE.CS_ID_DIAGNOSIS
    JOIN PATIENT ON PATIENT.PATIENT_ID = MEDICAL_CASE.PATIENT_ID
    JOIN DOCTOR ON DOCTOR.DOCTOR_ID = MEDICAL_CASE.DOCTOR_ID_REF
    GROUP BY HOSPITAL.NAME, CLASSIFICATION_SYSTEM.NAME;

SELECT DOCTOR.SURNAME AS Doctor, CLASSIFICATION_SYSTEM.NAME AS Diagnosis, COUNT(MEDICAL_CASE.MEDICAL_CASE_ID) AS Number_of_Cases
FROM MEDICAL_CASE
JOIN HOSPITAL ON HOSPITAL.HOSPITAL_ID = MEDICAL_CASE.HOSPITAL_ID
JOIN CLASSIFICATION_SYSTEM ON CLASSIFICATION_SYSTEM.CS_ID = MEDICAL_CASE.CS_ID_DIAGNOSIS
JOIN PATIENT ON PATIENT.PATIENT_ID = MEDICAL_CASE.PATIENT_ID
JOIN DOCTOR ON DOCTOR.DOCTOR_ID = MEDICAL_CASE.DOCTOR_ID_REF
GROUP BY DOCTOR.SURNAME, CLASSIFICATION_SYSTEM.NAME
ORDER BY Number_of_Cases DESC ;

SELECT DOCTOR.SURNAME AS Doctor,
    SUM(CLASSIFICATION_SYSTEM.CS_ID = 1020395
        ) AS Diagnosis1_Count

FROM MEDICAL_CASE
JOIN HOSPITAL ON HOSPITAL.HOSPITAL_ID = MEDICAL_CASE.HOSPITAL_ID
JOIN CLASSIFICATION_SYSTEM ON CLASSIFICATION_SYSTEM.CS_ID = MEDICAL_CASE.CS_ID_DIAGNOSIS
JOIN PATIENT ON PATIENT.PATIENT_ID = MEDICAL_CASE.PATIENT_ID
JOIN DOCTOR ON DOCTOR.DOCTOR_ID = MEDICAL_CASE.DOCTOR_ID_REF
GROUP BY DOCTOR.SURNAME
ORDER BY Diagnosis1_Count DESC ;