use elga;

select HOSPITAL.NAME, CLASSIFICATION_SYSTEM.NAME
from  HOSPITAL,MEDICAL_CASE,CLASSIFICATION_SYSTEM
WHERE HOSPITAL.HOSPITAL_ID = MEDICAL_CASE.HOSPITAL_ID && MEDICAL_CASE.CS_ID_DIAGNOSIS = CLASSIFICATION_SYSTEM.CS_ID
GROUP BY HOSPITAL.NAME;



SELECT *
FROM MEDICAL_CASE
JOIN HOSPITAL ON HOSPITAL.HOSPITAL_ID = MEDICAL_CASE.HOSPITAL_ID
JOIN CLASSIFICATION_SYSTEM ON CLASSIFICATION_SYSTEM.CS_ID = MEDICAL_CASE.CS_ID_DIAGNOSIS
JOIN PATIENT ON PATIENT.PATIENT_ID = MEDICAL_CASE.PATIENT_ID
JOIN DOCTOR ON DOCTOR.DOCTOR_ID = MEDICAL_CASE.DOCTOR_ID_REF;

SELECT HOSPITAL.NAME AS Hospital, CLASSIFICATION_SYSTEM.NAME AS Diagnosis, COUNT(MEDICAL_CASE.MEDICAL_CASE_ID) AS Case_Count
    FROM HOSPITAL
    JOIN MEDICAL_CASE ON HOSPITAL.HOSPITAL_ID = MEDICAL_CASE.HOSPITAL_ID
    JOIN CLASSIFICATION_SYSTEM ON CLASSIFICATION_SYSTEM.CS_ID = MEDICAL_CASE.CS_ID_DIAGNOSIS
    JOIN PATIENT ON PATIENT.PATIENT_ID = MEDICAL_CASE.PATIENT_ID
    JOIN DOCTOR ON DOCTOR.DOCTOR_ID = MEDICAL_CASE.DOCTOR_ID_REF
    GROUP BY HOSPITAL.NAME, CLASSIFICATION_SYSTEM.NAME;

SELECT DOCTOR.SURNAME AS Doctor, CLASSIFICATION_SYSTEM.NAME AS Diagnosis, COUNT(MEDICAL_CASE.MEDICAL_CASE_ID) AS Number_of_Cases
FROM MEDICAL_CASE
JOIN HOSPITAL ON HOSPITAL.HOSPITAL_ID = MEDICAL_CASE.HOSPITAL_ID
JOIN CLASSIFICATION_SYSTEM ON CLASSIFICATION_SYSTEM.CS_ID = MEDICAL_CASE.CS_ID_DIAGNOSIS
JOIN PATIENT ON PATIENT.PATIENT_ID = MEDICAL_CASE.PATIENT_ID
JOIN DOCTOR ON DOCTOR.DOCTOR_ID = MEDICAL_CASE.DOCTOR_ID_REF
GROUP BY DOCTOR.SURNAME, CLASSIFICATION_SYSTEM.NAME
ORDER BY Number_of_Cases DESC ;

SELECT DOCTOR.SURNAME AS Doctor,
    SUM(CLASSIFICATION_SYSTEM.CS_ID = 1020395
        ) AS Diagnosis1_Count

FROM MEDICAL_CASE
JOIN HOSPITAL ON HOSPITAL.HOSPITAL_ID = MEDICAL_CASE.HOSPITAL_ID
JOIN CLASSIFICATION_SYSTEM ON CLASSIFICATION_SYSTEM.CS_ID = MEDICAL_CASE.CS_ID_DIAGNOSIS
JOIN PATIENT ON PATIENT.PATIENT_ID = MEDICAL_CASE.PATIENT_ID
JOIN DOCTOR ON DOCTOR.DOCTOR_ID = MEDICAL_CASE.DOCTOR_ID_REF
GROUP BY DOCTOR.SURNAME
ORDER BY Diagnosis1_Count DESC ;

--  Rang eines Arztes basierend auf der Anzahl der Fälle pro Krankenhaus:SELECT DOCTOR.SURNAME AS Surname, HOSPITAL.NAME, COUNT(MEDICAL_CASE_ID) AS CASE_COUNT,
SELECT DOCTOR.SURNAME AS Surname, HOSPITAL.NAME_SHORT, COUNT(MEDICAL_CASE_ID) AS CASE_COUNT,
       RANK() OVER (PARTITION BY MEDICAL_CASE.HOSPITAL_ID ORDER BY COUNT(MEDICAL_CASE_ID) DESC) AS DOCTOR_RANK
FROM MEDICAL_CASE
         JOIN DOCTOR ON MEDICAL_CASE.DOCTOR_ID_REF = DOCTOR.DOCTOR_ID
         JOIN HOSPITAL ON MEDICAL_CASE.HOSPITAL_ID = HOSPITAL.HOSPITAL_ID
GROUP BY DOCTOR.SURNAME, HOSPITAL.NAME, MEDICAL_CASE.HOSPITAL_ID;

--  kumulative Summe der Anzahl der medizinischen Fälle pro Arzt über die Zeit:

SELECT DOCTOR.SURNAME, MEDICAL_CASE.DATE_CREATED, COUNT(MEDICAL_CASE.MEDICAL_CASE_ID) AS CASE_COUNT,
       SUM(COUNT(MEDICAL_CASE.MEDICAL_CASE_ID)) OVER (PARTITION BY DOCTOR.DOCTOR_ID ORDER BY MEDICAL_CASE.DATE_CREATED) AS CUMULATIVE_COUNT
FROM MEDICAL_CASE
         JOIN DOCTOR ON MEDICAL_CASE.DOCTOR_ID_REF = DOCTOR.DOCTOR_ID
GROUP BY DOCTOR.SURNAME, MEDICAL_CASE.DATE_CREATED, DOCTOR.DOCTOR_ID;
--  vorherige Diagnose für jeden medizinischen Fall an, gruppiert nach Patient und sortiert nach Datum:
SELECT P.SURNAME AS PATIENT_SURNAME, CS.NAME AS DIAGNOSIS_NAME, M.DATE_CREATED,
       LAG(CS.NAME) OVER (PARTITION BY M.PATIENT_ID ORDER BY M.DATE_CREATED) AS PREVIOUS_DIAGNOSIS
FROM MEDICAL_CASE M
         JOIN PATIENT P ON M.PATIENT_ID = P.PATIENT_ID
         JOIN CLASSIFICATION_SYSTEM CS ON M.CS_ID_DIAGNOSIS = CS.CS_ID
ORDER BY P.PATIENT_ID, M.DATE_CREATED;
--  durchschnittliche Anzahl von Fällen pro Patient und Krankenhaus:
SELECT P.SURNAME AS SURNAME,P.FIRSTNAME AS FIRSTNAME, H.NAME AS HOSPITAL_NAME,
       COUNT(M.MEDICAL_CASE_ID) AS CASE_COUNT,
       AVG(COUNT(M.MEDICAL_CASE_ID)) OVER (PARTITION BY P.PATIENT_ID, M.HOSPITAL_ID) AS AVG_CASE_COUNT
FROM MEDICAL_CASE M
         JOIN PATIENT P ON M.PATIENT_ID = P.PATIENT_ID
         JOIN HOSPITAL H ON M.HOSPITAL_ID = H.HOSPITAL_ID
GROUP BY P.PATIENT_ID, M.HOSPITAL_ID, H.NAME, P.SURNAME;
--  kumulative Summe der Anzahl der Fälle pro Arzt und Krankenhaus, sortiert nach Datum:

SELECT D.SURNAME AS SURNAME, H.NAME AS HOSPITAL_NAME, M.DATE_CREATED, COUNT(M.MEDICAL_CASE_ID) AS CASE_COUNT,
       SUM(COUNT(M.MEDICAL_CASE_ID)) OVER (PARTITION BY D.DOCTOR_ID, M.HOSPITAL_ID ORDER BY M.DATE_CREATED) AS CUMULATIVE_COUNT,
       MCD.NAME AS MEDICAL_CASE
FROM MEDICAL_CASE M
         JOIN DOCTOR D ON M.DOCTOR_ID_REF = D.DOCTOR_ID
         JOIN HOSPITAL H ON M.HOSPITAL_ID = H.HOSPITAL_ID
         JOIN CLASSIFICATION_SYSTEM MCD ON M.CS_ID_DIAGNOSIS = MCD.CS_ID
GROUP BY D.DOCTOR_ID, M.HOSPITAL_ID, H.NAME, D.SURNAME, M.DATE_CREATED, MCD.CS_ID;




